name: CI

on:

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        
  download:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
       with:
         repository: 'noa_kfir/d'

     - uses: actions/download-artifact@v2
       with:
         name: my-artifact
         path: path/to/artifact/world.txt


