name: action

on: [push]
 
jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "github-actions-test-noa" 
          heroku_email: "noa.kfir@aquant.io"
          buildpack: "https://github.com/heroku/heroku-buildpack-python"
      - name: set up python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
      - name: run code
        run: python source/code.py  
        


         



      
      
  
    