name: CI

on:

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'noakfir/GitActions'
        token: ${{ secrets.PERSONAL_TOKEN}}
        persist-credentials: false 
        fetch-depth: 0 
    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
    - name: Commit files
      run: |
        git config --local user.email "noa.kfir@aquant.io"
        git config --local user.name "noakfir"
        git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/noakfir/GitActions
        git checkout "noakfir/GitActions"
        git add .
        git commit -m "Add changes" -a
        git push
