name: CI

on:

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
         repository: 'noakfir/GitActions'
         token: ${{ secrets.PERSONAL_TOKEN }}
         path: 'GitActions'

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
        
    - name: update file and push to remote
      run: |

        git config --global user.name "noakfir"
        git config --global user.email "noa.kfir@aquant.io"

        git add -A
        git commit -m "first try"
        git push
